language: c
sudo: false
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/
git:
  depth: false
  quiet: true
before_install:
   - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
   - echo -e "Trying to get dependency" && [[ ! -d $HOME/arduino_ide/libraries/ESP32_AnalogWrite ]] && git clone https://github.com/ERROPiX/ESP32_AnalogWrite $HOME/arduino_ide/libraries/ESP32_AnalogWrite && echo -e "Dependency downloaded"
install:
   - arduino --install-library "DHT sensor library","Adafruit Unified Sensor"
script:
  - build_platform uno
  - build_platform esp32
notifications:
  email: false
